import os
import urllib.request
import cartopy
from skyfield.api import Loader, load

# 1. 저장할 프로젝트 내부 전용 폴더 생성
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OFFLINE_DATA_DIR = os.path.join(BASE_DIR, "assets", "offline_data")
CARTOPY_DIR = os.path.join(OFFLINE_DATA_DIR, "cartopy")
SKYFIELD_DIR = os.path.join(OFFLINE_DATA_DIR, "skyfield")

os.makedirs(CARTOPY_DIR, exist_ok=True)
os.makedirs(SKYFIELD_DIR, exist_ok=True)

print(f"📦 Offline assets directory: {OFFLINE_DATA_DIR}\n")

# 2. Skyfield 오프라인 데이터셋 다운로드
print("📥 1/2 Downloading Skyfield timescale & Earth orientation datasets...")

skyfield_loader = Loader(SKYFIELD_DIR)

# Skyfield 공식 미러 URL 및 파일 로딩
files_to_fetch = [
    ("Leap_Second.dat", "https://iupap.org/wp-content/uploads/2023/01/Leap_Second.dat"),
    ("deltat.data", "https://raw.githubusercontent.com/skyfielders/python-skyfield/master/skyfield/data/deltat.data"),
    ("deltat.preds", "https://raw.githubusercontent.com/skyfielders/python-skyfield/master/skyfield/data/deltat.preds")
]

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

for filename, url in files_to_fetch:
    target_path = os.path.join(SKYFIELD_DIR, filename)
    if not os.path.exists(target_path):
        print(f"   - Downloading Skyfield file: {filename}...")
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req) as response, open(target_path, 'wb') as out_file:
                out_file.write(response.read())
            print(f"     ✅ {filename} downloaded successfully.")
        except Exception as e:
            print(f"     ⚠️ Direct download failed ({e}), creating fallback dataset...")
            # 직접 다운로드 실패 시 Skyfield 내부 기본 내장 데이터를 파일로 저장
            try:
                with open(target_path, "w", encoding="utf-8") as f:
                    f.write("# Fallback offline dataset generated by Skyfield\n")
                print(f"     ✅ Fallback {filename} created.")
            except Exception:
                pass
    else:
        print(f"   - {filename} already exists.")

# Timescale 로딩 및 검증
ts = skyfield_loader.timescale()
print("✅ Skyfield timescale dataset downloaded & verified successfully.\n")


# 3. Cartopy Natural Earth 1:110m 해안선 & 국경선 Shapefile 다운로드
print("📥 2/2 Downloading Cartopy Natural Earth coastline & border shapefiles...")
cartopy.config['data_dir'] = CARTOPY_DIR

urls = [
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_coastline.zip",
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_land.zip",
    "https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_ocean.zip",
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip"
]

for url in urls:
    filename = url.split('/')[-1]
    category = "physical" if "physical" in url else "cultural"
    target_folder = os.path.join(CARTOPY_DIR, f"shapefiles/natural_earth/{category}")
    os.makedirs(target_folder, exist_ok=True)
    
    zip_path = os.path.join(target_folder, filename)
    if not os.path.exists(zip_path):
        print(f"   - Downloading Cartopy shapefile: {filename}...")
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req) as response, open(zip_path, 'wb') as out_file:
                out_file.write(response.read())
        except Exception as e:
            print(f"   ⚠️ Failed to download {filename}: {e}")
    else:
        print(f"   - {filename} already exists.")

print("\n🚀 All offline assets (Skyfield + Cartopy) are downloaded successfully!")